### ISSUE TITLE
Tunnel states

### ISSUE THREAD

**Issue by timcras** [zward/Amua#32]
How can I use tunnel states? For example, if a patient needs to have a scan at year 1 and 5, but not at years 2-4, how can I program it in Amua that when at year 1 and 5 the patient goes to 'Scan' in the Markov model, but at years 2-4 it goes to 'No Scan'. Thanks in advance!

**Comment by zward** [comment]
Is Scan really a Markov State, or an event that happens during a cycle?  Something like this:

![image](https://user-images.githubusercontent.com/5375573/58717166-9d5e9580-8398-11e9-8a2c-5a79e5848e95.png)

Either way, you could have a variable `pScan` which varies the probability of scan by time by using:
- An if function, for example: `pScan = if(t==1 | t==5, 1, 0)`  This will return 1 in cycles 1 and 5 and 0 otherwise
- A lookup table, for example: `pScan = tableScan[t,1]`  where `tableScan` looks like

|Index|Value|
|------|------|
|0       |0       |
|1       |1       |
|2       |0       |
|3       |0       |
|4       |0       |
|5       |1       |
|6       |0       |

and you would use the truncate option.

Would one of those approaches work?

**Comment by timcras** [comment]
Hi Zach,

The scan is indeed more an event than it is a Markov State. I have tried your approach and it seems to work perfectly! Thank you very much for your help.

Best regards,
Tim

**Comment by zward** [comment]
Good to hear.  I will close this issue then.
