### ISSUE TITLE
PSA

### ISSUE THREAD

**Issue by MariaLuna20** [zward/Amua#42]
Hello, I'm trying to run a PSA but it is running extremely slowly (10 iterations were going to take ~1 hour) and once I stopped the PSA then the model is not longer checking correctly (even though it was checking ok before the PSA). Do you know why the PSA is so slow and is there something happening internally for an aborted PSA to alter the model?

Thank you!!
L.

**Comment by zward** [comment]
The model check after cancelled PSA might be due to a variable checking issue - if so, this should be fixed in the next version, coming soon, so you can see if that solves the problem once it is released.
The PSA just loops the model and samples from parameters for each iteration, so unless you have a lot of constraints which affect parameter sampling, the PSA time should scale linearly with the number of model iterations.  How long does one run of the model take?
To speed it up, you could try reducing the number of Monte Carlo simulations (i.e. number of individuals to simulate),  or you could try using multi-threading to see if you get better performance.

**Comment by MariaLuna20** [comment]
Thank you for your response, I tried reducing the simulations and multi-threading but that didn’t help. The model runs instantly when clicking on the green arrow at the top of the screen but it is when I try to run the PSA that is extremely slow. Do you have any other suggestions?
When is the next version coming out?
Thanks!

**Comment by zward** [comment]
The new version should be out next week.
That seems strange that one run of the model is quick but that PSA is so slow.  Can you send me a copy of the model (zward@hsph.harvard.edu) so that I can test it on my system?  Also, can you check how much memory you have available in Amua? (Go to Help -> Error Log and find the line near the bottom that says "Heap - Max Memory")

**Comment by zward** [comment]
I think this was due to an issue with dependent parameter re-sampling that was slowing things down.  This should be fixed now as of 0.2.7.
